server:
  port: 8081
  servlet:
    context-path: /yingx
    jsp:
      init-parameters:
        development: ture #开启jsp开发模式修改页面刷新


# 配置跳转视图的前后缀
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/mysql?useUnicode=true&characterEncoding=UTF8
    username: root
    password: 123456
      #配置连接es地址
  data:
    elasticsearch:
       cluster-nodes: 192.168.107.141:9300
  redis:
    host: localhost
    port: 6379

  servlet:
    multipart:
      max-file-size: 1000MB
      max-request-size: 1000MB
  #mvc:
   # hiddenmethod:
     # filter:
       # enabled: true

logging:
  level:
    com.baizhi.dao: debug
# mybatis相关的依赖
mybatis-plus:
  mapper-locations: mapper/*Mapper.xml
  type-aliases-package: com.baizhi.entity